import {readFile,writeFile,mkdir,readdir,rename} from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';

export const origin='https://kalikatools.com';
export const categories=['Mantra','Chalisa','Stotra','Aarti','Scripture','Prayer'];
export const languages={sa:'Sanskrit',hi:'Hindi',awa:'Awadhi',ne:'Nepali',en:'English',other:'Other'};
export const fields=['slug','title','nativeTitle','category','language','summary','introduction','verses','transliteration','meaning','background','readingNotes','sourceLabel','sourceUrl','credit','seoTitle','description'];
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function normalize(input){const result={};for(const key of fields)result[key]=String(input[key]??'').replace(/\r\n?/g,'\n').trim();return result;}
export function validate(input,publishing=false){
 const d=normalize(input);
 if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.slug)||d.slug.length<3||d.slug.length>80||['index','new','admin'].includes(d.slug))throw Error('Use an address of 3–80 lowercase letters, numbers and hyphens.');
 if(!d.title||d.title.length>150)throw Error('Enter a title up to 150 characters.');
 if(!categories.includes(d.category)||!languages[d.language])throw Error('Choose a category and text language.');
 for(const [key,value]of Object.entries(d)){const max=['verses','meaning','background','transliteration','readingNotes'].includes(key)?100000: key==='introduction'?10000:1000;if(value.length>max)throw Error(`${key} exceeds the supported length (${max.toLocaleString()} characters).`);}
 if(d.sourceUrl){let u;try{u=new URL(d.sourceUrl)}catch{}if(!u||u.protocol!=='https:'||u.username||u.password)throw Error('Source links must be valid HTTPS addresses.');}
 if(publishing){
  for(const key of ['summary','introduction','verses','meaning','sourceLabel','credit'])if(!d[key])throw Error(`Complete ${key} before publishing.`);
  if(d.seoTitle.length<50||d.seoTitle.length>60)throw Error('Write an SEO title of 50–60 characters.');
  if(d.description.length<140||d.description.length>160)throw Error('Write a search description of 140–160 characters.');
 }
 return d;
}
export const revision=d=>createHash('sha256').update(JSON.stringify(normalize(d))).digest('hex');
export async function atomicJson(file,data){
 await mkdir(path.dirname(file),{recursive:true});const temp=file+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(data,null,2)+'\n');
 // Windows can briefly lock the destination while it is being read or scanned.
 for(let attempt=0;;attempt++){try{await rename(temp,file);return;}catch(e){if(!['EPERM','EACCES','EBUSY'].includes(e.code)||attempt>=10)throw e;await new Promise(r=>setTimeout(r,50*(attempt+1)));}}
}
export async function readEntries(root,folder='content/traditional-texts'){
 const dir=path.join(root,folder);let names;try{names=await readdir(dir)}catch(e){if(e.code==='ENOENT')return [];throw e;}
 return Promise.all(names.filter(n=>n.endsWith('.json')).map(async name=>{const d=JSON.parse(await readFile(path.join(dir,name),'utf8'));validate(d);if(name!==d.slug+'.json')throw Error('An entry has an invalid filename.');return d;}));
}
const paragraphs=text=>String(text||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${escape(p).replaceAll('\n','<br>')}</p>`).join('');
const safeJson=data=>JSON.stringify(data).replaceAll('<','\\u003c');
export async function chrome(root){const ref=await readFile(path.join(root,'public/tools/nepali-typing.html'),'utf8');return {header:ref.match(/<header[\s\S]*?<\/header>/)[0],footer:ref.match(/<footer[\s\S]*?<\/footer>/)[0]};}
function head(title,description,url,schema,preview=false){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${url}">${preview?'<meta name="robots" content="noindex,nofollow">':''}<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/texts.css"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${url}"><meta property="og:type" content="${url.endsWith('/texts/')?'website':'article'}"><meta property="og:site_name" content="Kalika"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><script type="application/ld+json">${safeJson(schema)}</script>${preview?'':'<script defer src="/main.js"></script><script defer src="/js/i18n.js"></script><script defer src="/js/texts.js"></script>'}</head>`;}
export function renderEntry(d,layout,{preview=false}={}){
 const url=origin+'/texts/'+d.slug,lang=d.language==='other'?'und':d.language;
 const schema={'@context':'https://schema.org','@type':'Article',headline:d.title,description:d.description,inLanguage:['en',lang],datePublished:d.publishedAt||undefined,dateModified:d.updatedAt||undefined,author:{'@type':'Organization',name:'Kalika'},publisher:{'@type':'Organization',name:'Kalika',url:origin},mainEntityOfPage:url};
 const optional=[['transliteration','Pronunciation guide'],['meaning','Meaning in plain language'],['background','Background & tradition'],['readingNotes','Reading notes']].filter(([key])=>d[key]);
 return head(d.seoTitle||d.title,d.description||d.summary,url,schema,preview)+`<body class="texts-page"><a class="skip" href="#main">Skip to content</a>${layout.header}<main id="main" class="wrap reading-wrap" data-content-revision="${revision(d)}"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/texts/">Traditional texts</a> / ${escape(d.title)}</nav><header class="reading-header" translate="no"><p class="overline">${escape(d.category)} · ${escape(languages[d.language])}</p>${d.nativeTitle?`<p class="native-title" lang="${lang}">${escape(d.nativeTitle)}</p>`:''}<h1>${escape(d.title)}</h1><p class="reading-deck">${escape(d.summary)}</p>${d.updatedAt?`<p class="reading-date">Updated <time datetime="${escape(d.updatedAt)}">${new Date(d.updatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}</time></p>`:''}</header><div class="reading-layout"><aside class="reading-nav" aria-label="On this page"><p class="overline">On this page</p><a href="#original-text">Original text</a>${optional.map(([key,title])=>`<a href="#${key}">${title}</a>`).join('')}<a href="#sources">Source & attribution</a><div class="reading-controls"><button type="button" id="text-smaller" aria-label="Smaller text">A−</button><button type="button" id="text-larger" aria-label="Larger text">A+</button><button type="button" id="print-text">Print</button></div></aside><article class="reading-content" translate="no"><section class="reading-intro">${paragraphs(d.introduction)}</section><section id="original-text" class="verse-panel"><p class="overline">पाठ · Original text</p><h2>${escape(d.nativeTitle||'Original text')}</h2><div class="original-verses" lang="${lang}">${escape(d.verses)}</div><div class="verse-actions"><button type="button" id="copy-verses">Copy text</button><span id="reader-status" role="status"></span></div></section>${optional.map(([key,title])=>`<section id="${key}" class="reading-section"><h2>${title}</h2>${paragraphs(d[key])}</section>`).join('')}<section id="sources" class="reading-section source-note"><h2>Source & attribution</h2><p>${d.sourceUrl?`<a href="${escape(d.sourceUrl)}" target="_blank" rel="noopener noreferrer">${escape(d.sourceLabel)}</a>`:escape(d.sourceLabel)}</p>${paragraphs(d.credit)}</section><p class="back-library"><a href="/texts/">← Explore traditional Hindu texts</a></p></article></div></main>${layout.footer}</body></html>`;
}
export function renderLibrary(entries,layout){
 const title='Traditional Hindu Texts, Mantras & Meanings | Kalika';
 const description='Read traditional Hindu prayers, Sanskrit mantras and devotional texts with original verses, pronunciation, meanings and source notes in the Kalika text library.';
 const sorted=[...entries].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));
 const schema={'@context':'https://schema.org','@type':'CollectionPage',name:'Traditional Hindu Texts',url:origin+'/texts/',description,mainEntity:{'@type':'ItemList',itemListElement:sorted.map((d,i)=>({'@type':'ListItem',position:i+1,url:origin+'/texts/'+d.slug,name:d.title}))}};
 return head(title,description,origin+'/texts/',schema)+`<body class="texts-page"><a class="skip" href="#main">Skip to content</a>${layout.header}<main id="main" class="wrap"><section class="library-hero"><div class="library-emblem" aria-hidden="true">ॐ</div><p class="overline">KALIKA · A LIBRARY FOR REFLECTION</p><h1>Traditional Hindu texts</h1><p class="native-title" lang="sa" translate="no">श्रद्धा · अध्ययन · मनन</p><p class="library-deck">A quiet place to read, understand, and return to the words of tradition. Explore original prayers and devotional texts, with pronunciation, meaning, and sources alongside them.</p></section><section class="library-browser" aria-label="Browse texts"><div class="library-heading"><div><p class="overline">THE COLLECTION</p><h2>Read with understanding.</h2></div><p>${entries.length} ${entries.length===1?'text':'texts'} · Growing thoughtfully</p></div><div class="library-filters"><label>Find a text<input id="text-search" type="search" placeholder="Search by title, deity or phrase…"></label><label>Category<select id="text-category"><option value="all">All texts</option>${categories.map(c=>`<option>${c}</option>`).join('')}</select></label></div><div class="text-cards">${sorted.map(d=>`<a class="text-card" href="/texts/${d.slug}" data-category="${escape(d.category)}" data-search="${escape([d.title,d.nativeTitle,d.summary,d.category].join(' ').toLowerCase())}" translate="no"><div class="text-card-top"><span>${escape(d.category)}</span><span>${escape(languages[d.language])}</span></div>${d.nativeTitle?`<p class="card-native" lang="${d.language==='other'?'und':d.language}">${escape(d.nativeTitle)}</p>`:''}<h3>${escape(d.title)}</h3><p>${escape(d.summary)}</p><span class="read-link">Read text <span aria-hidden="true">↗</span></span></a>`).join('')}</div><p id="no-text-results" role="status" hidden>No matching texts yet. Try another title or choose All texts.</p>${entries.length?'':'<p>Our first texts are being prepared. Please visit again soon.</p>'}</section><section class="library-principles"><div><h2>Rooted in tradition.<br>Presented with care.</h2></div><div><p>Original words sit beside clearly labelled explanations. Each entry identifies its language and source, so you can explore the text in context.</p><p>Wording and recitation can vary between traditions. Source notes preserve those distinctions. This collection is for reading and reflection, with space for the practices of your own family and community.</p></div></section></main>${layout.footer}</body></html>`;
}
export async function buildLibrary(root){
 const entries=await readEntries(root);entries.forEach(d=>validate(d,true));const layout=await chrome(root),dir=path.join(root,'public/texts');await mkdir(dir,{recursive:true});
 for(const d of entries)await writeFile(path.join(dir,d.slug+'.html'),renderEntry(d,layout));
 await writeFile(path.join(dir,'index.html'),renderLibrary(entries,layout));
 const file=path.join(root,'public/sitemap.xml');let sitemap=await readFile(file,'utf8');sitemap=sitemap.replace(/<url>\s*<loc>https:\/\/kalikatools\.com\/texts(?:\/[^<]*)?<\/loc>[\s\S]*?<\/url>/g,'');
 sitemap=sitemap.replace('</urlset>',`<url><loc>${origin}/texts/</loc></url>${entries.map(d=>`<url><loc>${origin}/texts/${d.slug}</loc><lastmod>${escape(d.updatedAt.slice(0,10))}</lastmod></url>`).join('')}</urlset>`);await writeFile(file,sitemap);
 return entries;
}
