import fs from 'node:fs/promises';import {gzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
const config=JSON.parse(await fs.readFile('config/ocr-vendor.json','utf8'));
for(const [name,version] of [['tesseract.js',config.tesseractVersion],['tesseract.js-core',config.coreVersion]])if(JSON.parse(await fs.readFile('node_modules/'+name+'/package.json','utf8')).version!==version)throw Error('Installed '+name+' differs from pinned OCR version. Run npm ci.');
const base='public/js/vendor/ocr';await fs.mkdir(base+'/core',{recursive:true});await fs.mkdir(base+'/languages',{recursive:true});
for(const name of ['worker.min.js'])await fs.copyFile('node_modules/tesseract.js/dist/'+name,base+'/'+name);
for(const name of await fs.readdir('node_modules/tesseract.js-core'))if(name.endsWith('.wasm.js'))await fs.copyFile('node_modules/tesseract.js-core/'+name,base+'/core/'+name);
await fs.copyFile('node_modules/tesseract.js/LICENSE.md',base+'/TESSERACT-LICENSE.txt');await fs.copyFile('node_modules/tesseract.js-core/LICENSE',base+'/CORE-LICENSE.txt');
const revision=config.modelRevision;
for(const lang of config.languages){const r=await fetch('https://raw.githubusercontent.com/tesseract-ocr/tessdata_fast/'+revision+'/'+lang+'.traineddata');if(!r.ok)throw Error(lang+' unavailable');const data=gzipSync(Buffer.from(await r.arrayBuffer()),{level:9});await fs.writeFile(base+'/languages/'+lang+'.traineddata.gz',data);console.log(lang,(data.length/1048576).toFixed(2)+' MiB');}
const license=await fetch('https://raw.githubusercontent.com/tesseract-ocr/tessdata_fast/'+revision+'/LICENSE');if(!license.ok)throw Error('Missing model license');await fs.writeFile(base+'/languages/LICENSE.txt',await license.text());
await fs.writeFile(base+'/README.txt',`Tesseract.js 7.0.0 and tesseract.js-core ${JSON.parse(await fs.readFile('node_modules/tesseract.js-core/package.json')).version}.\nSources: https://github.com/naptha/tesseract.js and https://github.com/naptha/tesseract.js-core\nModels: https://github.com/tesseract-ocr/tessdata_fast/tree/${revision}\nEnglish, French, Spanish, Hindi, Nepali and Simplified Chinese.\nApache-2.0 licenses included. All assets self-hosted; only the selected core and languages load on demand.\n`);
async function walk(d){return (await Promise.all((await fs.readdir(d,{withFileTypes:true})).map(e=>e.isDirectory()?walk(d+'/'+e.name):d+'/'+e.name))).flat();}const manifest=JSON.parse(await fs.readFile('config/vendor-integrity.json','utf8'));for(const file of await walk(base)){let bytes=await fs.readFile(file);if(/\.(m?js|txt)$|LICENSE/.test(file))bytes=Buffer.from(bytes.toString('utf8').replace(/\r\n/g,'\n'));manifest[file]=createHash('sha256').update(bytes).digest('hex');}await fs.writeFile('config/vendor-integrity.json',JSON.stringify(manifest,null,2)+'\n');console.log('Vendored OCR assets and pinned integrity manifest.');
